version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - gallatin-internal

  postgres-service:
    container_name: postgres-service
    image: postgres:latest
    restart: always
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    volumes:
      - ./web/misc/postgres:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 5
    networks:
      - gallatin-internal

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
    networks:
      - gallatin-internal

  # Gallatin Service
  gallatin:
    build: .
    container_name: task-manager-gallatin_linux_amd64
    environment:
      - CONFIG_PATH=/app/config.yaml
    depends_on:
      - postgres-service
      - cache
      - rabbitmq
    ports:
      - "50051:50051"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./CreateDB.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - gallatin-internal

volumes:
  pgdata:
  cache:
    driver: local

networks:
  gallatin-internal: